const photos = [
  "https://concord-assets.oss-cn-beijing.aliyuncs.com/201003%20updates/1.JPG",
  "https://concord-assets.oss-cn-beijing.aliyuncs.com/201003%20updates/10.JPG",
  "https://concord-assets.oss-cn-beijing.aliyuncs.com/201003%20updates/11.JPG",
  "https://concord-assets.oss-cn-beijing.aliyuncs.com/201003%20updates/2.jpg",
  "https://concord-assets.oss-cn-beijing.aliyuncs.com/201003%20updates/3.jpg",
  "https://concord-assets.oss-cn-beijing.aliyuncs.com/201003%20updates/4.jpg",
  "https://concord-assets.oss-cn-beijing.aliyuncs.com/201003%20updates/5.jpg",
  "https://concord-assets.oss-cn-beijing.aliyuncs.com/201003%20updates/6.jpg",
  "https://concord-assets.oss-cn-beijing.aliyuncs.com/201003%20updates/7.JPG",
  "https://concord-assets.oss-cn-beijing.aliyuncs.com/201003%20updates/8.JPG",
  "https://concord-assets.oss-cn-beijing.aliyuncs.com/201003%20updates/9.JPG",
  'http://concord-assets.oss-cn-beijing.aliyuncs.com/191111_img_8.png',
  'http://concord-assets.oss-cn-beijing.aliyuncs.com/191111_img_9.png',
  'http://concord-assets.oss-cn-beijing.aliyuncs.com/191111_img_10.png',
  'http://concord-assets.oss-cn-beijing.aliyuncs.com/191111_img_11.png',
  'https://concord-assets.oss-cn-beijing.aliyuncs.com/performance-1.jpg',
  'http://concord-assets.oss-cn-beijing.aliyuncs.com/experience__boy-voilen.jpg',
  'http://concord-assets.oss-cn-beijing.aliyuncs.com/experience__classroom.jpg',
  'https://concord-assets.oss-cn-beijing.aliyuncs.com/performance-2.jpg',
  'http://concord-assets.oss-cn-beijing.aliyuncs.com/experience__drums.jpg',
  'http://concord-assets.oss-cn-beijing.aliyuncs.com/experience__fei-piano-2.jpg',
  'http://concord-assets.oss-cn-beijing.aliyuncs.com/experience__fei-piano.jpg',
  'http://concord-assets.oss-cn-beijing.aliyuncs.com/experience__fei-teaching.jpg',
  'https://concord-assets.oss-cn-beijing.aliyuncs.com/performance-3.jpg',
  'http://concord-assets.oss-cn-beijing.aliyuncs.com/experience__flowers.jpg',
  'http://concord-assets.oss-cn-beijing.aliyuncs.com/experience__gavin-teaching.jpg',
  'http://concord-assets.oss-cn-beijing.aliyuncs.com/experience__hallway.jpg',
  'http://concord-assets.oss-cn-beijing.aliyuncs.com/experience__learning-at-concord.jpg',
]

export default photos
